### ISSUE TITLE
Configuração

### ISSUE THREAD

**Issue by lucasrv** [cte-zl-ifrn/portal__ava#6]
Bom dia, sou do IFTO, estamos tentando implantar o portal_ava aqui e estou com algumas dúvidas:

O que coloco na variável SUAP_CLIENT_ID
Depois de subir todos os containers e fazer a autenticação no portal_ava, qual seria o próximo passo?
Vi que houve uma mudança a algumas horas, agora devo subir tudo com o compose? Não é necessário rodar o backs nem o debug?

**Comment by cte-ead** [comment]
Bom dia, @lucasrv .

Nos distraímos e não vimos sua issue antes. Isso foi resolvido ou você ainda necessita de ajuda?
